version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    on-failure: ABORT
    commands:
      # The folowing environment variables must be defined:
      # SONAR_HOST_URL : The URL for SonarQube (e.g. : https://sonarqube.yourdomain.com)
      # SONAR_TOKEN : The SonarQube issued credential with permissions to update (or create) this project in SonarQube.
      - node src/waitForApplication.mjs --application $SONAR_HOST_URL --verbose
      - npm run sonar
  post_build:
    commands:
      - echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > .npmrc
      - npm publish --access public
artifacts:
  files:
