version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    on-failure: ABORT
    commands:
      - npm run test
      # The folowing environment variables must be defined:
      # SONAR_HOST_URL : The URL for SonarQube (e.g. : https://sonarqube.yourdomain.com)
      # SONAR_TOKEN : The SonarQube issued credential with permissions to update (or create) this project in SonarQube.
      - npm run sonar
  post_build:
    on-failure: ABORT
    commands:
      # The folowing environment variable must be defined:
      # NPM_TOKEN : Token issued by npmjs.com with permissions to publish this package.
      - echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > .npmrc
      - git config user.email "aws-codebuild@ijot.nl"
      - git config user.name "AWS Codebuild"
      - npm version patch
      - npm publish --access public
      # @@TODO: The next statement fails (pushing version update back to GitHub).
      - git push origin main
