version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install node-fetch
      - npm install yargs
      # SonarQube is needed for the build script, not as part of the package.
      - npm install --location=global sonarqube-scanner
  build:
    commands:
      - node src/waitForApplication.mjs --application $SONAR_HOST_URL --verbose
      - sonar-scanner
        -Dsonar.projectKey=$SONAR_PROJECT
        -Dsonar.sources=.
        -Dsonar.exclusions=**/test/*,coverage/**/*,node_modules/**/*,test-report.xml
        -Dsonar.tests=.
        -Dsonar.test.inclusions=**/test/*
  post_build:
    commands:
artifacts:
  files:
